# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import re
import sysv_ipc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QDialog

import sys


class Ui_MainWindow(QDialog):
    fname = None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 552)
        # loadUi("gui.ui",self)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 661, 31))
        self.plainTextEdit.setPlainText("")

        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 10, 131, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Click_Browse)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 140, 131, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Click_Convert_HTML)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 180, 131, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2.clicked.connect(self.toC)

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 661, 451))
        self.textBrowser.setObjectName("textBrowser")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.pushButton_2.setText(_translate("MainWindow", "Convert to HTML"))
        self.pushButton_3.setText(_translate("MainWindow", "Send to C program"))

    def Click_Browse(self):
         print(os.getcwd())

         Ui_MainWindow.fname = QFileDialog.getOpenFileName(self, 'Open file', os.getcwd())
         print(Ui_MainWindow.fname[0])
         f = open(Ui_MainWindow.fname[0], "r")
         print(str)
         self.textBrowser.setText(f.read())


         with open("received.html", "w") as e:
             for lines in f.readlines():
                 e.write("<pre>" + lines + "</pre> <br>\n")

         # self.plainTextEdit.setPlainText(f.read())
         # self.filename.setText(fname[0])


    def toHTML(self):
        k = "<HTML><HEAD><TITLE>SERIALIZER</TITLE></HEAD><BODY>"
        text = open(self.file_path).readlines()
        for i in text:
            i = re.sub("\n", "", i)
            x = re.sub(i, "<p><h1>" + i + "</h1></p>\n", i)
            k = k + x
        k = k + "</BODY></HTML>"
        self.textEdit.setPlainText(k)
        f=open(self.file_path, "a")
        f.seek(0)
        f.truncate()
        f.write(k)
        f.close()
        print(k)

    def toC(self):
        def send_message(message_queue, message):
            message_queue.send(message)
        try:
            # put the key (integer) as parameter (in this case: -1)
            message_queue = sysv_ipc.MessageQueue(-1)
            send_message(message_queue, "received.html")
        except sysv_ipc.ExistentialError:
            print("Message queue not initialized. Please run the C program first")

    def Click_Convert_HTML(self):

        if(Ui_MainWindow.fname != None):
            f = open(Ui_MainWindow.fname[0], "r")
            with open("received.html", "w") as e:
                for lines in f.readlines():
                    e.write("<pre>" + lines + "</pre> <br>\n")

            f = open("received.html", "r")
            self.textBrowser.setText(f.read())


if __name__ == "__main__":
    # fname = None
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
